"""Regenerate the frontend cache from final domain code; never hand-edit metrics."""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from apps.api.dashboard import build_dashboard

if __name__ == "__main__":
    state = build_dashboard()
    state["data_mode"] = "cached"
    target = ROOT / "dashboard/src/lib/demo-state.ts"
    target.write_text(
        "import type { DashboardState } from './types';\n\n// Generated by scripts/export_dashboard_snapshot.py from domain outputs.\nexport const DEMO_DASHBOARD_STATE: DashboardState = "
        + json.dumps(state, indent=2, allow_nan=False)
        + ";\n",
        encoding="utf-8",
    )
    print("Generated", target.relative_to(ROOT))
    plan = state["cleaner"]["cleanup_plan"]
    print(
        json.dumps(
            {
                k: plan[k]
                for k in (
                    "total_distance_km",
                    "estimated_collection_kg",
                    "capacity_utilization",
                    "completion_time_hours",
                )
            }
        )
    )
