import type { DashboardState } from './types';

// Generated by scripts/export_dashboard_snapshot.py from domain outputs.
export const DEMO_DASHBOARD_STATE: DashboardState = {
  "scenario_id": "scenario_hero_01",
  "last_updated": null,
  "data_mode": "cached",
  "source_health": {
    "sentinel": {
      "status": "partial-live",
      "detail": "GFW identity API authenticated and cached. Exact hero identity/events remain unverified, so displayed cases stay labelled simulated."
    },
    "marine": {
      "status": "live-cached",
      "detail": "Open-Meteo forecast refreshed live and cached for shared NAVIGATOR/CLEANER use; single-site approximation."
    },
    "protected_areas": {
      "status": "unverified",
      "detail": "Bundled demo boundary; official geometry lineage unverified."
    },
    "noaa": {
      "status": "reference",
      "detail": "Shoreline survey context only; not offshore observations."
    },
    "copernicus": {
      "status": "auth-failed",
      "detail": "Official client reached Copernicus authentication, which rejected the supplied login; retained offline baseline."
    },
    "cleaner": {
      "status": "simulated",
      "detail": "Curated targets and simulated USVs; derived mission estimates."
    }
  },
  "sentinel": {
    "cases": [
      {
        "vessel_id": "vessel_hero_01",
        "name": "FU YUAN YU 882",
        "flag": "CN",
        "event_time": "2024-01-15T04:32:00Z",
        "gap_start": "2024-01-14T10:00:00Z",
        "gap_end": "2024-01-15T04:30:00Z",
        "gap_hours": 18.5,
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
              [
                -90.5,
                -0.2
              ],
              [
                -89.5,
                -0.2
              ],
              [
                -89.5,
                0.8
              ],
              [
                -90.5,
                0.8
              ],
              [
                -90.5,
                -0.2
              ]
            ]
          ]
        },
        "protected_area_relation": "near",
        "fishing_signal": true,
        "loitering_signal": true,
        "repeat_count": 2,
        "risk_score": 89.19,
        "risk_level": "CRITICAL",
        "evidence": [
          {
            "feature": "ais_gap_hours",
            "value": 18.5,
            "points": 19.27,
            "source": "GFW Events API v3",
            "explanation": "AIS transponder was silent for 18.5 hours -- contributes 19.27 risk points."
          },
          {
            "feature": "fishing_near_mpa",
            "value": true,
            "points": 25.0,
            "source": "GFW Events API v3",
            "explanation": "Apparent fishing detected near a Marine Protected Area -- significant concern for illegal, unreported, or unregulated (IUU) fishing."
          },
          {
            "feature": "protected_area_proximity",
            "value": "near",
            "points": 15.92,
            "source": "Protected Planet WDPA",
            "explanation": "Vessel is 10.2 km from the nearest MPA boundary."
          },
          {
            "feature": "loitering_behaviour",
            "value": true,
            "points": 15.0,
            "source": "GFW Events API v3",
            "explanation": "Vessel exhibited loitering behaviour -- extended period at < 3 knots near MPA boundary waters."
          },
          {
            "feature": "repeat_offender",
            "value": 2,
            "points": 4.0,
            "source": "Historical Records",
            "explanation": "2 prior incident(s) on record -- contributes 4 risk points."
          },
          {
            "feature": "calm_weather_ais_gap",
            "value": 0.6,
            "points": 5.0,
            "source": "Copernicus Marine CMEMS (offline baseline \u2014 Galapagos, Jan 2024)",
            "explanation": "AIS gap of 18.5 h occurred in calm seas (SWH 0.6 m) \u2014 no meteorological justification for transponder disable."
          },
          {
            "feature": "fishing_environment",
            "value": 0.45,
            "points": 5.0,
            "source": "Copernicus Marine CMEMS (offline baseline \u2014 Galapagos, Jan 2024)",
            "explanation": "High-productivity fishing environment detected: CHL 0.450 mg/m\u00b3, SST anomaly +1.2 \u00b0C \u2014 significant overlap with known IUU fishing attractor zone."
          }
        ],
        "confidence": 0.93,
        "timeline": [],
        "provenance": null
      },
      {
        "vessel_id": "vessel_highenv_01",
        "name": "SHENG FA 8",
        "flag": "CN",
        "event_time": "2024-01-16T02:15:00Z",
        "gap_start": "2024-01-15T18:00:00Z",
        "gap_end": "2024-01-16T02:00:00Z",
        "gap_hours": 8.0,
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
              [
                -86.82,
                1.65
              ],
              [
                -85.78,
                1.65
              ],
              [
                -85.78,
                2.55
              ],
              [
                -86.82,
                2.55
              ],
              [
                -86.82,
                1.65
              ]
            ]
          ]
        },
        "protected_area_relation": "near",
        "fishing_signal": true,
        "loitering_signal": false,
        "repeat_count": 1,
        "risk_score": 56.93,
        "risk_level": "HIGH",
        "evidence": [
          {
            "feature": "ais_gap_hours",
            "value": 8.0,
            "points": 8.33,
            "source": "GFW Events API v3",
            "explanation": "AIS transponder was silent for 8.0 hours -- contributes 8.33 risk points."
          },
          {
            "feature": "fishing_near_mpa",
            "value": true,
            "points": 25.0,
            "source": "GFW Events API v3",
            "explanation": "Apparent fishing detected near a Marine Protected Area -- significant concern for IUU fishing."
          },
          {
            "feature": "protected_area_proximity",
            "value": "near",
            "points": 11.6,
            "source": "Protected Planet WDPA",
            "explanation": "Vessel is 21.8 km from the nearest MPA boundary."
          },
          {
            "feature": "repeat_offender",
            "value": 1,
            "points": 2.0,
            "source": "Historical Records",
            "explanation": "1 prior incident(s) on record -- contributes 2 risk points."
          },
          {
            "feature": "calm_weather_ais_gap",
            "value": 0.8,
            "points": 5.0,
            "source": "Copernicus Marine CMEMS (live)",
            "explanation": "AIS gap of 8.0 h occurred in calm seas (SWH 0.8 m) \u2014 no meteorological justification for transponder disable."
          },
          {
            "feature": "fishing_environment",
            "value": 0.72,
            "points": 5.0,
            "source": "Copernicus Marine CMEMS (live)",
            "explanation": "High-productivity fishing environment detected: CHL 0.720 mg/m\u00b3, SST anomaly +1.8 \u00b0C \u2014 significant overlap with known IUU fishing attractor zone."
          }
        ],
        "confidence": 0.82,
        "timeline": [],
        "provenance": null
      },
      {
        "vessel_id": "vessel_storm_01",
        "name": "NOVA PESCA 3",
        "flag": "VE",
        "event_time": "2024-01-17T09:00:00Z",
        "gap_start": "2024-01-16T20:00:00Z",
        "gap_end": "2024-01-17T09:00:00Z",
        "gap_hours": 13.0,
        "geometry": {
          "type": "Point",
          "coordinates": [
            -79.5,
            8.2
          ]
        },
        "protected_area_relation": "outside",
        "fishing_signal": false,
        "loitering_signal": false,
        "repeat_count": 0,
        "risk_score": 13.54,
        "risk_level": "LOW",
        "evidence": [
          {
            "feature": "ais_gap_hours",
            "value": 13.0,
            "points": 13.54,
            "source": "GFW Events API v3",
            "explanation": "AIS transponder was silent for 13.0 hours -- contributes 13.54 risk points."
          }
        ],
        "confidence": 0.42,
        "timeline": [],
        "provenance": null
      },
      {
        "vessel_id": "vessel_control_02",
        "name": "PACIFIC EXPLORER",
        "flag": "PA",
        "event_time": "2024-01-15T08:15:00Z",
        "gap_start": "2024-01-15T06:00:00Z",
        "gap_end": "2024-01-15T08:00:00Z",
        "gap_hours": 2.0,
        "geometry": {
          "type": "Point",
          "coordinates": [
            -88.0,
            0.5
          ]
        },
        "protected_area_relation": "outside",
        "fishing_signal": false,
        "loitering_signal": false,
        "repeat_count": 0,
        "risk_score": 2.08,
        "risk_level": "LOW",
        "evidence": [
          {
            "feature": "ais_gap_hours",
            "value": 2.0,
            "points": 2.08,
            "source": "GFW Events API v3",
            "explanation": "AIS transponder was silent for 2.0 hours -- contributes 2.08 risk points."
          }
        ],
        "confidence": 0.35,
        "timeline": [],
        "provenance": null
      },
      {
        "vessel_id": "vessel_control_01",
        "name": "MAERSK SELETAR",
        "flag": "SG",
        "event_time": "2024-01-15T12:00:00Z",
        "gap_start": null,
        "gap_end": null,
        "gap_hours": 0.0,
        "geometry": {
          "type": "Point",
          "coordinates": [
            -89.0,
            1.5
          ]
        },
        "protected_area_relation": "outside",
        "fishing_signal": false,
        "loitering_signal": false,
        "repeat_count": 0,
        "risk_score": 0.0,
        "risk_level": "LOW",
        "evidence": [],
        "confidence": 0.3,
        "timeline": [],
        "provenance": null
      }
    ],
    "risk_zones": [
      {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -90.5,
              -0.2
            ],
            [
              -89.5,
              -0.2
            ],
            [
              -89.5,
              0.8
            ],
            [
              -90.5,
              0.8
            ],
            [
              -90.5,
              -0.2
            ]
          ]
        ]
      },
      {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -86.82,
              1.65
            ],
            [
              -85.78,
              1.65
            ],
            [
              -85.78,
              2.55
            ],
            [
              -86.82,
              2.55
            ],
            [
              -86.82,
              1.65
            ]
          ]
        ]
      }
    ],
    "protected_areas": [
      {
        "type": "Feature",
        "properties": {
          "wdpa_id": 317180,
          "name": "Galapagos Marine Reserve",
          "designation": "Marine Reserve",
          "iucn_category": "VI",
          "country": "ECU",
          "status": "Designated",
          "source": "Protected Planet WDPA (demo/cache extract)"
        },
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
              [
                -92.0,
                -1.8
              ],
              [
                -91.0,
                -1.8
              ],
              [
                -90.0,
                -1.5
              ],
              [
                -89.5,
                -1.0
              ],
              [
                -89.2,
                -0.5
              ],
              [
                -89.2,
                0.0
              ],
              [
                -89.5,
                0.5
              ],
              [
                -90.0,
                0.8
              ],
              [
                -90.5,
                0.8
              ],
              [
                -91.0,
                0.5
              ],
              [
                -91.5,
                0.0
              ],
              [
                -92.0,
                -0.5
              ],
              [
                -92.0,
                -1.8
              ]
            ]
          ]
        }
      }
    ]
  },
  "navigator": {
    "route_result": {
      "baseline_polyline": [
        [
          -88.5789,
          1.2368
        ],
        [
          -88.8947,
          0.9211
        ],
        [
          -89.2105,
          0.6053
        ],
        [
          -89.5263,
          0.2895
        ],
        [
          -89.5263,
          -0.0263
        ],
        [
          -89.8421,
          -0.3421
        ],
        [
          -90.1579,
          -0.6579
        ],
        [
          -90.4737,
          -0.9737
        ],
        [
          -90.7895,
          -1.2895
        ],
        [
          -91.1053,
          -1.6053
        ],
        [
          -91.4211,
          -1.9211
        ]
      ],
      "optimized_polyline": [
        [
          -88.5789,
          1.2368
        ],
        [
          -88.8947,
          0.9211
        ],
        [
          -89.2105,
          0.6053
        ],
        [
          -89.2105,
          0.2895
        ],
        [
          -89.2105,
          -0.0263
        ],
        [
          -88.8947,
          -0.3421
        ],
        [
          -89.2105,
          -0.6579
        ],
        [
          -89.5263,
          -0.6579
        ],
        [
          -89.8421,
          -0.9737
        ],
        [
          -90.1579,
          -1.2895
        ],
        [
          -90.4737,
          -1.6053
        ],
        [
          -90.7895,
          -1.9211
        ],
        [
          -91.1053,
          -1.9211
        ],
        [
          -91.4211,
          -1.9211
        ]
      ],
      "distance_km": 572.78,
      "eta_hours": 22.09,
      "fuel_proxy": 590.71,
      "weather_cost": 228.6,
      "security_cost": 0.0,
      "total_cost": 145.57,
      "comparison": {
        "baseline_distance_km": 482.02,
        "optimized_distance_km": 572.78,
        "distance_delta_pct": 18.83,
        "baseline_eta_hours": 18.59,
        "optimized_eta_hours": 22.09,
        "eta_delta_pct": 18.83,
        "baseline_fuel_proxy": 482.02,
        "optimized_fuel_proxy": 590.71,
        "fuel_delta_pct": 22.55,
        "baseline_security_exposure": "HIGH",
        "optimized_security_exposure": "ZERO",
        "security_exposure_delta_pct": -100.0,
        "baseline_security_cost": 6721.78,
        "optimized_security_cost": 0.0,
        "objective_time_cost_hours": 22.8145,
        "mode": "optimized"
      },
      "environment_samples": [
        {
          "lon": -88.5789,
          "lat": 1.2368,
          "time": "2026-09-12T00:00",
          "wave_height_m": 1.72,
          "wave_direction_deg": 170.0,
          "wave_period_s": 8.95,
          "current_speed_ms": 0.4167,
          "current_direction_deg": 353.0,
          "sst_c": 26.6,
          "source": "open-meteo",
          "data_quality": "good"
        },
        {
          "lon": -88.7368,
          "lat": 1.0789,
          "time": "2026-09-12T00:00",
          "wave_height_m": 1.72,
          "wave_direction_deg": 170.0,
          "wave_period_s": 8.95,
          "current_speed_ms": 0.4167,
          "current_direction_deg": 353.0,
          "sst_c": 26.6,
          "source": "open-meteo",
          "data_quality": "good"
        },
        {
          "lon": -88.8947,
          "lat": 0.9211,
          "time": "2026-09-12T00:00",
          "wave_height_m": 1.72,
          "wave_direction_deg": 170.0,
          "wave_period_s": 8.95,
          "current_speed_ms": 0.4167,
          "current_direction_deg": 353.0,
          "sst_c": 26.6,
          "source": "open-meteo",
          "data_quality": "good"
        },
        {
          "lon": -89.0526,
          "lat": 0.7632,
          "time": "2026-09-12T00:00",
          "wave_height_m": 1.72,
          "wave_direction_deg": 170.0,
          "wave_period_s": 8.95,
          "current_speed_ms": 0.4167,
          "current_direction_deg": 353.0,
          "sst_c": 26.6,
          "source": "open-meteo",
          "data_quality": "good"
        },
        {
          "lon": -89.2105,
          "lat": 0.6053,
          "time": "2026-09-12T00:00",
          "wave_height_m": 1.72,
          "wave_direction_deg": 170.0,
          "wave_period_s": 8.95,
          "current_speed_ms": 0.4167,
          "current_direction_deg": 353.0,
          "sst_c": 26.6,
          "source": "open-meteo",
          "data_quality": "good"
        },
        {
          "lon": -89.2105,
          "lat": 0.4474,
          "time": "2026-09-12T00:00",
          "wave_height_m": 1.72,
          "wave_direction_deg": 170.0,
          "wave_period_s": 8.95,
          "current_speed_ms": 0.4167,
          "current_direction_deg": 353.0,
          "sst_c": 26.6,
          "source": "open-meteo",
          "data_quality": "good"
        },
        {
          "lon": -89.2105,
          "lat": 0.2895,
          "time": "2026-09-12T00:00",
          "wave_height_m": 1.72,
          "wave_direction_deg": 170.0,
          "wave_period_s": 8.95,
          "current_speed_ms": 0.4167,
          "current_direction_deg": 353.0,
          "sst_c": 26.6,
          "source": "open-meteo",
          "data_quality": "good"
        },
        {
          "lon": -89.2105,
          "lat": 0.1316,
          "time": "2026-09-12T00:00",
          "wave_height_m": 1.72,
          "wave_direction_deg": 170.0,
          "wave_period_s": 8.95,
          "current_speed_ms": 0.4167,
          "current_direction_deg": 353.0,
          "sst_c": 26.6,
          "source": "open-meteo",
          "data_quality": "good"
        },
        {
          "lon": -89.2105,
          "lat": -0.0263,
          "time": "2026-09-12T00:00",
          "wave_height_m": 1.72,
          "wave_direction_deg": 170.0,
          "wave_period_s": 8.95,
          "current_speed_ms": 0.4167,
          "current_direction_deg": 353.0,
          "sst_c": 26.6,
          "source": "open-meteo",
          "data_quality": "good"
        },
        {
          "lon": -89.0526,
          "lat": -0.1842,
          "time": "2026-09-12T00:00",
          "wave_height_m": 1.72,
          "wave_direction_deg": 170.0,
          "wave_period_s": 8.95,
          "current_speed_ms": 0.4167,
          "current_direction_deg": 353.0,
          "sst_c": 26.6,
          "source": "open-meteo",
          "data_quality": "good"
        },
        {
          "lon": -88.8947,
          "lat": -0.3421,
          "time": "2026-09-12T00:00",
          "wave_height_m": 1.72,
          "wave_direction_deg": 170.0,
          "wave_period_s": 8.95,
          "current_speed_ms": 0.4167,
          "current_direction_deg": 353.0,
          "sst_c": 26.6,
          "source": "open-meteo",
          "data_quality": "good"
        },
        {
          "lon": -89.0526,
          "lat": -0.5,
          "time": "2026-09-12T00:00",
          "wave_height_m": 1.72,
          "wave_direction_deg": 170.0,
          "wave_period_s": 8.95,
          "current_speed_ms": 0.4167,
          "current_direction_deg": 353.0,
          "sst_c": 26.6,
          "source": "open-meteo",
          "data_quality": "good"
        }
      ],
      "current_vectors": [
        {
          "lon": -88.5789,
          "lat": 1.2368,
          "u_ms": -0.0508,
          "v_ms": 0.4136,
          "speed_ms": 0.4167,
          "direction_deg": 353.0,
          "source": "open-meteo"
        },
        {
          "lon": -88.7368,
          "lat": 1.0789,
          "u_ms": -0.0508,
          "v_ms": 0.4136,
          "speed_ms": 0.4167,
          "direction_deg": 353.0,
          "source": "open-meteo"
        },
        {
          "lon": -88.8947,
          "lat": 0.9211,
          "u_ms": -0.0508,
          "v_ms": 0.4136,
          "speed_ms": 0.4167,
          "direction_deg": 353.0,
          "source": "open-meteo"
        },
        {
          "lon": -89.0526,
          "lat": 0.7632,
          "u_ms": -0.0508,
          "v_ms": 0.4136,
          "speed_ms": 0.4167,
          "direction_deg": 353.0,
          "source": "open-meteo"
        },
        {
          "lon": -89.2105,
          "lat": 0.6053,
          "u_ms": -0.0508,
          "v_ms": 0.4136,
          "speed_ms": 0.4167,
          "direction_deg": 353.0,
          "source": "open-meteo"
        },
        {
          "lon": -89.2105,
          "lat": 0.4474,
          "u_ms": -0.0508,
          "v_ms": 0.4136,
          "speed_ms": 0.4167,
          "direction_deg": 353.0,
          "source": "open-meteo"
        },
        {
          "lon": -89.2105,
          "lat": 0.2895,
          "u_ms": -0.0508,
          "v_ms": 0.4136,
          "speed_ms": 0.4167,
          "direction_deg": 353.0,
          "source": "open-meteo"
        },
        {
          "lon": -89.2105,
          "lat": 0.1316,
          "u_ms": -0.0508,
          "v_ms": 0.4136,
          "speed_ms": 0.4167,
          "direction_deg": 353.0,
          "source": "open-meteo"
        },
        {
          "lon": -89.2105,
          "lat": -0.0263,
          "u_ms": -0.0508,
          "v_ms": 0.4136,
          "speed_ms": 0.4167,
          "direction_deg": 353.0,
          "source": "open-meteo"
        },
        {
          "lon": -89.0526,
          "lat": -0.1842,
          "u_ms": -0.0508,
          "v_ms": 0.4136,
          "speed_ms": 0.4167,
          "direction_deg": 353.0,
          "source": "open-meteo"
        },
        {
          "lon": -88.8947,
          "lat": -0.3421,
          "u_ms": -0.0508,
          "v_ms": 0.4136,
          "speed_ms": 0.4167,
          "direction_deg": 353.0,
          "source": "open-meteo"
        },
        {
          "lon": -89.0526,
          "lat": -0.5,
          "u_ms": -0.0508,
          "v_ms": 0.4136,
          "speed_ms": 0.4167,
          "direction_deg": 353.0,
          "source": "open-meteo"
        }
      ],
      "risk_intersections": null,
      "cost_decomposition": {
        "baseline": {
          "fuel_cost": 482.02,
          "time_cost": 18.59,
          "weather_cost": 0.0,
          "security_cost": 6721.78,
          "wave_exposure": 0.0,
          "current_effect": 0.0
        },
        "optimized": {
          "fuel_cost": 590.71,
          "time_cost": 22.81,
          "weather_cost": 228.6,
          "security_cost": 0.0,
          "wave_exposure": 215.15,
          "current_effect": -2.8
        }
      },
      "reroute_reason": "Optimized route deviates to reduce composite cost (longer distance; lower security cost; avoids risk polygon).",
      "data_quality_status": "good",
      "route_id": "route_hero_01",
      "route_version": "1.0",
      "changed_at": "2026-09-12T12:00:00Z",
      "trigger": "Risk zone updated"
    }
  },
  "environment": {
    "samples": [
      {
        "time": "2026-09-12T00:00",
        "lat": 1.2368,
        "lon": -88.5789,
        "wave_height_m": 1.72,
        "wave_direction_deg": 170.0,
        "wave_period_s": 8.95,
        "current_u_ms": -0.0508,
        "current_v_ms": 0.4136,
        "current_speed_ms": 0.4167,
        "current_direction_deg": 353.0,
        "sst_c": 26.6,
        "source": "open-meteo",
        "provenance": {
          "source_name": "open-meteo",
          "source_mode": "forecast",
          "cached": true,
          "observed_at": "2026-09-12T00:00",
          "retrieved_at": "2026-09-12T16:14:09Z",
          "notes": "Live-refreshed marine cache; single-site field extrapolated over the corridor."
        },
        "data_quality": "good",
        "retrieval_time": "2026-09-12T16:14:09Z"
      },
      {
        "time": "2026-09-12T00:00",
        "lat": 0.9211,
        "lon": -88.8947,
        "wave_height_m": 1.72,
        "wave_direction_deg": 170.0,
        "wave_period_s": 8.95,
        "current_u_ms": -0.0508,
        "current_v_ms": 0.4136,
        "current_speed_ms": 0.4167,
        "current_direction_deg": 353.0,
        "sst_c": 26.6,
        "source": "open-meteo",
        "provenance": {
          "source_name": "open-meteo",
          "source_mode": "forecast",
          "cached": true,
          "observed_at": "2026-09-12T00:00",
          "retrieved_at": "2026-09-12T16:14:09Z",
          "notes": "Live-refreshed marine cache; single-site field extrapolated over the corridor."
        },
        "data_quality": "good",
        "retrieval_time": "2026-09-12T16:14:09Z"
      },
      {
        "time": "2026-09-12T00:00",
        "lat": 0.6053,
        "lon": -89.2105,
        "wave_height_m": 1.72,
        "wave_direction_deg": 170.0,
        "wave_period_s": 8.95,
        "current_u_ms": -0.0508,
        "current_v_ms": 0.4136,
        "current_speed_ms": 0.4167,
        "current_direction_deg": 353.0,
        "sst_c": 26.6,
        "source": "open-meteo",
        "provenance": {
          "source_name": "open-meteo",
          "source_mode": "forecast",
          "cached": true,
          "observed_at": "2026-09-12T00:00",
          "retrieved_at": "2026-09-12T16:14:09Z",
          "notes": "Live-refreshed marine cache; single-site field extrapolated over the corridor."
        },
        "data_quality": "good",
        "retrieval_time": "2026-09-12T16:14:09Z"
      },
      {
        "time": "2026-09-12T00:00",
        "lat": 0.2895,
        "lon": -89.2105,
        "wave_height_m": 1.72,
        "wave_direction_deg": 170.0,
        "wave_period_s": 8.95,
        "current_u_ms": -0.0508,
        "current_v_ms": 0.4136,
        "current_speed_ms": 0.4167,
        "current_direction_deg": 353.0,
        "sst_c": 26.6,
        "source": "open-meteo",
        "provenance": {
          "source_name": "open-meteo",
          "source_mode": "forecast",
          "cached": true,
          "observed_at": "2026-09-12T00:00",
          "retrieved_at": "2026-09-12T16:14:09Z",
          "notes": "Live-refreshed marine cache; single-site field extrapolated over the corridor."
        },
        "data_quality": "good",
        "retrieval_time": "2026-09-12T16:14:09Z"
      },
      {
        "time": "2026-09-12T00:00",
        "lat": -0.0263,
        "lon": -89.2105,
        "wave_height_m": 1.72,
        "wave_direction_deg": 170.0,
        "wave_period_s": 8.95,
        "current_u_ms": -0.0508,
        "current_v_ms": 0.4136,
        "current_speed_ms": 0.4167,
        "current_direction_deg": 353.0,
        "sst_c": 26.6,
        "source": "open-meteo",
        "provenance": {
          "source_name": "open-meteo",
          "source_mode": "forecast",
          "cached": true,
          "observed_at": "2026-09-12T00:00",
          "retrieved_at": "2026-09-12T16:14:09Z",
          "notes": "Live-refreshed marine cache; single-site field extrapolated over the corridor."
        },
        "data_quality": "good",
        "retrieval_time": "2026-09-12T16:14:09Z"
      },
      {
        "time": "2026-09-12T00:00",
        "lat": -0.3421,
        "lon": -88.8947,
        "wave_height_m": 1.72,
        "wave_direction_deg": 170.0,
        "wave_period_s": 8.95,
        "current_u_ms": -0.0508,
        "current_v_ms": 0.4136,
        "current_speed_ms": 0.4167,
        "current_direction_deg": 353.0,
        "sst_c": 26.6,
        "source": "open-meteo",
        "provenance": {
          "source_name": "open-meteo",
          "source_mode": "forecast",
          "cached": true,
          "observed_at": "2026-09-12T00:00",
          "retrieved_at": "2026-09-12T16:14:09Z",
          "notes": "Live-refreshed marine cache; single-site field extrapolated over the corridor."
        },
        "data_quality": "good",
        "retrieval_time": "2026-09-12T16:14:09Z"
      },
      {
        "time": "2026-09-12T00:00",
        "lat": -0.6579,
        "lon": -89.2105,
        "wave_height_m": 1.72,
        "wave_direction_deg": 170.0,
        "wave_period_s": 8.95,
        "current_u_ms": -0.0508,
        "current_v_ms": 0.4136,
        "current_speed_ms": 0.4167,
        "current_direction_deg": 353.0,
        "sst_c": 26.6,
        "source": "open-meteo",
        "provenance": {
          "source_name": "open-meteo",
          "source_mode": "forecast",
          "cached": true,
          "observed_at": "2026-09-12T00:00",
          "retrieved_at": "2026-09-12T16:14:09Z",
          "notes": "Live-refreshed marine cache; single-site field extrapolated over the corridor."
        },
        "data_quality": "good",
        "retrieval_time": "2026-09-12T16:14:09Z"
      },
      {
        "time": "2026-09-12T00:00",
        "lat": -0.6579,
        "lon": -89.5263,
        "wave_height_m": 1.72,
        "wave_direction_deg": 170.0,
        "wave_period_s": 8.95,
        "current_u_ms": -0.0508,
        "current_v_ms": 0.4136,
        "current_speed_ms": 0.4167,
        "current_direction_deg": 353.0,
        "sst_c": 26.6,
        "source": "open-meteo",
        "provenance": {
          "source_name": "open-meteo",
          "source_mode": "forecast",
          "cached": true,
          "observed_at": "2026-09-12T00:00",
          "retrieved_at": "2026-09-12T16:14:09Z",
          "notes": "Live-refreshed marine cache; single-site field extrapolated over the corridor."
        },
        "data_quality": "good",
        "retrieval_time": "2026-09-12T16:14:09Z"
      },
      {
        "time": "2026-09-12T00:00",
        "lat": -0.9737,
        "lon": -89.8421,
        "wave_height_m": 1.72,
        "wave_direction_deg": 170.0,
        "wave_period_s": 8.95,
        "current_u_ms": -0.0508,
        "current_v_ms": 0.4136,
        "current_speed_ms": 0.4167,
        "current_direction_deg": 353.0,
        "sst_c": 26.6,
        "source": "open-meteo",
        "provenance": {
          "source_name": "open-meteo",
          "source_mode": "forecast",
          "cached": true,
          "observed_at": "2026-09-12T00:00",
          "retrieved_at": "2026-09-12T16:14:09Z",
          "notes": "Live-refreshed marine cache; single-site field extrapolated over the corridor."
        },
        "data_quality": "good",
        "retrieval_time": "2026-09-12T16:14:09Z"
      },
      {
        "time": "2026-09-12T00:00",
        "lat": -1.2895,
        "lon": -90.1579,
        "wave_height_m": 1.72,
        "wave_direction_deg": 170.0,
        "wave_period_s": 8.95,
        "current_u_ms": -0.0508,
        "current_v_ms": 0.4136,
        "current_speed_ms": 0.4167,
        "current_direction_deg": 353.0,
        "sst_c": 26.6,
        "source": "open-meteo",
        "provenance": {
          "source_name": "open-meteo",
          "source_mode": "forecast",
          "cached": true,
          "observed_at": "2026-09-12T00:00",
          "retrieved_at": "2026-09-12T16:14:09Z",
          "notes": "Live-refreshed marine cache; single-site field extrapolated over the corridor."
        },
        "data_quality": "good",
        "retrieval_time": "2026-09-12T16:14:09Z"
      },
      {
        "time": "2026-09-12T00:00",
        "lat": -1.6053,
        "lon": -90.4737,
        "wave_height_m": 1.72,
        "wave_direction_deg": 170.0,
        "wave_period_s": 8.95,
        "current_u_ms": -0.0508,
        "current_v_ms": 0.4136,
        "current_speed_ms": 0.4167,
        "current_direction_deg": 353.0,
        "sst_c": 26.6,
        "source": "open-meteo",
        "provenance": {
          "source_name": "open-meteo",
          "source_mode": "forecast",
          "cached": true,
          "observed_at": "2026-09-12T00:00",
          "retrieved_at": "2026-09-12T16:14:09Z",
          "notes": "Live-refreshed marine cache; single-site field extrapolated over the corridor."
        },
        "data_quality": "good",
        "retrieval_time": "2026-09-12T16:14:09Z"
      },
      {
        "time": "2026-09-12T00:00",
        "lat": -1.9211,
        "lon": -90.7895,
        "wave_height_m": 1.72,
        "wave_direction_deg": 170.0,
        "wave_period_s": 8.95,
        "current_u_ms": -0.0508,
        "current_v_ms": 0.4136,
        "current_speed_ms": 0.4167,
        "current_direction_deg": 353.0,
        "sst_c": 26.6,
        "source": "open-meteo",
        "provenance": {
          "source_name": "open-meteo",
          "source_mode": "forecast",
          "cached": true,
          "observed_at": "2026-09-12T00:00",
          "retrieved_at": "2026-09-12T16:14:09Z",
          "notes": "Live-refreshed marine cache; single-site field extrapolated over the corridor."
        },
        "data_quality": "good",
        "retrieval_time": "2026-09-12T16:14:09Z"
      },
      {
        "time": "2026-09-12T00:00",
        "lat": -1.9211,
        "lon": -91.1053,
        "wave_height_m": 1.72,
        "wave_direction_deg": 170.0,
        "wave_period_s": 8.95,
        "current_u_ms": -0.0508,
        "current_v_ms": 0.4136,
        "current_speed_ms": 0.4167,
        "current_direction_deg": 353.0,
        "sst_c": 26.6,
        "source": "open-meteo",
        "provenance": {
          "source_name": "open-meteo",
          "source_mode": "forecast",
          "cached": true,
          "observed_at": "2026-09-12T00:00",
          "retrieved_at": "2026-09-12T16:14:09Z",
          "notes": "Live-refreshed marine cache; single-site field extrapolated over the corridor."
        },
        "data_quality": "good",
        "retrieval_time": "2026-09-12T16:14:09Z"
      },
      {
        "time": "2026-09-12T00:00",
        "lat": -1.9211,
        "lon": -91.4211,
        "wave_height_m": 1.72,
        "wave_direction_deg": 170.0,
        "wave_period_s": 8.95,
        "current_u_ms": -0.0508,
        "current_v_ms": 0.4136,
        "current_speed_ms": 0.4167,
        "current_direction_deg": 353.0,
        "sst_c": 26.6,
        "source": "open-meteo",
        "provenance": {
          "source_name": "open-meteo",
          "source_mode": "forecast",
          "cached": true,
          "observed_at": "2026-09-12T00:00",
          "retrieved_at": "2026-09-12T16:14:09Z",
          "notes": "Live-refreshed marine cache; single-site field extrapolated over the corridor."
        },
        "data_quality": "good",
        "retrieval_time": "2026-09-12T16:14:09Z"
      },
      {
        "time": "2026-09-12T00:00",
        "lat": -0.49625,
        "lon": -90.2125,
        "wave_height_m": 1.72,
        "wave_direction_deg": 170.0,
        "wave_period_s": 8.95,
        "current_u_ms": -0.0508,
        "current_v_ms": 0.4136,
        "current_speed_ms": 0.4167,
        "current_direction_deg": 353.0,
        "sst_c": 26.6,
        "source": "open-meteo",
        "provenance": {
          "source_name": "open-meteo",
          "source_mode": "forecast",
          "cached": true,
          "observed_at": "2026-09-12T00:00",
          "retrieved_at": "2026-09-12T16:14:09Z",
          "notes": "Live-refreshed marine cache; single-site field extrapolated over the corridor."
        },
        "data_quality": "good",
        "retrieval_time": "2026-09-12T16:14:09Z"
      },
      {
        "time": "2026-09-12T00:00",
        "lat": -1.74875,
        "lon": -91.54875,
        "wave_height_m": 1.72,
        "wave_direction_deg": 170.0,
        "wave_period_s": 8.95,
        "current_u_ms": -0.0508,
        "current_v_ms": 0.4136,
        "current_speed_ms": 0.4167,
        "current_direction_deg": 353.0,
        "sst_c": 26.6,
        "source": "open-meteo",
        "provenance": {
          "source_name": "open-meteo",
          "source_mode": "forecast",
          "cached": true,
          "observed_at": "2026-09-12T00:00",
          "retrieved_at": "2026-09-12T16:14:09Z",
          "notes": "Live-refreshed marine cache; single-site field extrapolated over the corridor."
        },
        "data_quality": "good",
        "retrieval_time": "2026-09-12T16:14:09Z"
      },
      {
        "time": "2026-09-12T00:00",
        "lat": 0.86375,
        "lon": -88.885,
        "wave_height_m": 1.72,
        "wave_direction_deg": 170.0,
        "wave_period_s": 8.95,
        "current_u_ms": -0.0508,
        "current_v_ms": 0.4136,
        "current_speed_ms": 0.4167,
        "current_direction_deg": 353.0,
        "sst_c": 26.6,
        "source": "open-meteo",
        "provenance": {
          "source_name": "open-meteo",
          "source_mode": "forecast",
          "cached": true,
          "observed_at": "2026-09-12T00:00",
          "retrieved_at": "2026-09-12T16:14:09Z",
          "notes": "Live-refreshed marine cache; single-site field extrapolated over the corridor."
        },
        "data_quality": "good",
        "retrieval_time": "2026-09-12T16:14:09Z"
      }
    ],
    "valid_time": "2026-09-12T00:00"
  },
  "cleaner": {
    "clusters": [
      {
        "cluster_id": "cluster_01",
        "centroid": [
          -90.2125,
          -0.49625
        ],
        "estimated_mass_kg": 1250.0,
        "density": 3.0091,
        "impact_score": 86.08,
        "urgency": 0.98,
        "source": "curated_demo",
        "source_points": [
          [
            -90.28,
            -0.44
          ],
          [
            -90.22,
            -0.42
          ],
          [
            -90.16,
            -0.46
          ],
          [
            -90.11,
            -0.51
          ],
          [
            -90.18,
            -0.55
          ],
          [
            -90.24,
            -0.58
          ],
          [
            -90.31,
            -0.52
          ],
          [
            -90.2,
            -0.49
          ]
        ],
        "predicted_positions": [
          {
            "horizon_hours": 2,
            "position": [
              -90.2157858,
              -0.469499
            ],
            "source_badge": "DERIVED",
            "input_time": "2026-09-12T00:00",
            "valid_time": "2026-09-12T02:00:00",
            "source": "open-meteo"
          },
          {
            "horizon_hours": 6,
            "position": [
              -90.2223574,
              -0.415997
            ],
            "source_badge": "DERIVED",
            "input_time": "2026-09-12T00:00",
            "valid_time": "2026-09-12T06:00:00",
            "source": "open-meteo"
          },
          {
            "horizon_hours": 12,
            "position": [
              -90.2322147,
              -0.3357441
            ],
            "source_badge": "DERIVED",
            "input_time": "2026-09-12T00:00",
            "valid_time": "2026-09-12T12:00:00",
            "source": "open-meteo"
          }
        ],
        "drift_vector": {
          "current_u_ms": -0.0508,
          "current_v_ms": 0.4136,
          "source": "open-meteo",
          "input_time": "2026-09-12T00:00",
          "data_quality": "good",
          "drift_factor": 1.0
        },
        "observation_time": null,
        "provenance": {
          "source_name": "curated_demo",
          "source_mode": "simulated",
          "source_badge": "SIMULATED",
          "cached": true,
          "notes": "Curated offshore inputs; not NOAA floating-debris observations. Predictions are derived from a constant surface-current proxy.",
          "environment_source": "open-meteo",
          "environment_valid_time": "2026-09-12T00:00"
        }
      },
      {
        "cluster_id": "cluster_02",
        "centroid": [
          -91.54875,
          -1.74875
        ],
        "estimated_mass_kg": 835.0,
        "density": 1.5282,
        "impact_score": 76.13,
        "urgency": 0.9,
        "source": "curated_demo",
        "source_points": [
          [
            -91.62,
            -1.68
          ],
          [
            -91.56,
            -1.66
          ],
          [
            -91.49,
            -1.7
          ],
          [
            -91.44,
            -1.76
          ],
          [
            -91.5,
            -1.82
          ],
          [
            -91.58,
            -1.84
          ],
          [
            -91.66,
            -1.79
          ],
          [
            -91.54,
            -1.74
          ]
        ],
        "predicted_positions": [
          {
            "horizon_hours": 2,
            "position": [
              -91.5520372,
              -1.721999
            ],
            "source_badge": "DERIVED",
            "input_time": "2026-09-12T00:00",
            "valid_time": "2026-09-12T02:00:00",
            "source": "open-meteo"
          },
          {
            "horizon_hours": 6,
            "position": [
              -91.5586116,
              -1.668497
            ],
            "source_badge": "DERIVED",
            "input_time": "2026-09-12T00:00",
            "valid_time": "2026-09-12T06:00:00",
            "source": "open-meteo"
          },
          {
            "horizon_hours": 12,
            "position": [
              -91.5684732,
              -1.5882441
            ],
            "source_badge": "DERIVED",
            "input_time": "2026-09-12T00:00",
            "valid_time": "2026-09-12T12:00:00",
            "source": "open-meteo"
          }
        ],
        "drift_vector": {
          "current_u_ms": -0.0508,
          "current_v_ms": 0.4136,
          "source": "open-meteo",
          "input_time": "2026-09-12T00:00",
          "data_quality": "good",
          "drift_factor": 1.0
        },
        "observation_time": null,
        "provenance": {
          "source_name": "curated_demo",
          "source_mode": "simulated",
          "source_badge": "SIMULATED",
          "cached": true,
          "notes": "Curated offshore inputs; not NOAA floating-debris observations. Predictions are derived from a constant surface-current proxy.",
          "environment_source": "open-meteo",
          "environment_valid_time": "2026-09-12T00:00"
        }
      },
      {
        "cluster_id": "cluster_03",
        "centroid": [
          -88.885,
          0.86375
        ],
        "estimated_mass_kg": 690.0,
        "density": 1.0839,
        "impact_score": 65.15,
        "urgency": 0.81,
        "source": "curated_demo",
        "source_points": [
          [
            -88.96,
            0.76
          ],
          [
            -88.89,
            0.78
          ],
          [
            -88.82,
            0.82
          ],
          [
            -88.78,
            0.88
          ],
          [
            -88.84,
            0.94
          ],
          [
            -88.92,
            0.96
          ],
          [
            -89.0,
            0.91
          ],
          [
            -88.87,
            0.86
          ]
        ],
        "predicted_positions": [
          {
            "horizon_hours": 2,
            "position": [
              -88.888286,
              0.890501
            ],
            "source_badge": "DERIVED",
            "input_time": "2026-09-12T00:00",
            "valid_time": "2026-09-12T02:00:00",
            "source": "open-meteo"
          },
          {
            "horizon_hours": 6,
            "position": [
              -88.8948581,
              0.944003
            ],
            "source_badge": "DERIVED",
            "input_time": "2026-09-12T00:00",
            "valid_time": "2026-09-12T06:00:00",
            "source": "open-meteo"
          },
          {
            "horizon_hours": 12,
            "position": [
              -88.9047162,
              1.0242559
            ],
            "source_badge": "DERIVED",
            "input_time": "2026-09-12T00:00",
            "valid_time": "2026-09-12T12:00:00",
            "source": "open-meteo"
          }
        ],
        "drift_vector": {
          "current_u_ms": -0.0508,
          "current_v_ms": 0.4136,
          "source": "open-meteo",
          "input_time": "2026-09-12T00:00",
          "data_quality": "good",
          "drift_factor": 1.0
        },
        "observation_time": null,
        "provenance": {
          "source_name": "curated_demo",
          "source_mode": "simulated",
          "source_badge": "SIMULATED",
          "cached": true,
          "notes": "Curated offshore inputs; not NOAA floating-debris observations. Predictions are derived from a constant surface-current proxy.",
          "environment_source": "open-meteo",
          "environment_valid_time": "2026-09-12T00:00"
        }
      }
    ],
    "cleanup_plan": {
      "assignments": [
        {
          "usv_id": "usv_01",
          "cluster_id": "cluster_01",
          "selected": true,
          "feasible": true,
          "rejection_reasons": [],
          "intercept_point": [
            -90.2211706,
            -0.4256587
          ],
          "intercept_hours": 5.277657,
          "completion_hours": 10.555314,
          "range_margin_km": 22.26,
          "source_badge": "DERIVED",
          "mission_score": 0.712,
          "priority_score": 0.9304,
          "distance_km": 97.74,
          "travel_distance_km": 97.74,
          "estimated_collection_kg": 1250.0,
          "alternatives": [
            {
              "usv_id": "usv_01",
              "cluster_id": "cluster_01",
              "feasible": true,
              "rejection_reasons": [],
              "one_way_distance_km": 48.87,
              "travel_distance_km": 97.74,
              "priority_score": 0.9304,
              "travel_penalty": 0.1222,
              "capacity_penalty": 0.0962,
              "mission_score": 0.712,
              "intercept_point": [
                -90.2211706,
                -0.4256587
              ],
              "intercept_hours": 5.277657,
              "completion_hours": 10.555314,
              "range_margin_km": 22.26,
              "selected": true,
              "selection_reason": "best_feasible_mission_score"
            },
            {
              "usv_id": "usv_02",
              "cluster_id": "cluster_01",
              "feasible": false,
              "rejection_reasons": [
                "intercept_beyond_12h_forecast",
                "insufficient_range:requires_476.99km>remaining_95.00km",
                "insufficient_capacity:requires_1250.00kg>capacity_900.00kg"
              ],
              "one_way_distance_km": 238.5,
              "travel_distance_km": 476.99,
              "priority_score": 0.9304,
              "travel_penalty": 0.3,
              "capacity_penalty": 0.1389,
              "mission_score": 0.4915,
              "intercept_point": [
                -90.2322147,
                -0.3357441
              ],
              "intercept_hours": 12.0,
              "completion_hours": 51.510857,
              "range_margin_km": -381.99,
              "selected": false,
              "selection_reason": "infeasible"
            },
            {
              "usv_id": "usv_03",
              "cluster_id": "cluster_01",
              "feasible": false,
              "rejection_reasons": [
                "intercept_beyond_12h_forecast",
                "insufficient_range:requires_483.42km>remaining_90.00km",
                "insufficient_capacity:requires_1250.00kg>capacity_700.00kg"
              ],
              "one_way_distance_km": 241.71,
              "travel_distance_km": 483.42,
              "priority_score": 0.9304,
              "travel_penalty": 0.3,
              "capacity_penalty": 0.1786,
              "mission_score": 0.4518,
              "intercept_point": [
                -90.2322147,
                -0.3357441
              ],
              "intercept_hours": 12.0,
              "completion_hours": 52.205393,
              "range_margin_km": -393.42,
              "selected": false,
              "selection_reason": "infeasible"
            }
          ]
        },
        {
          "usv_id": "usv_02",
          "cluster_id": "cluster_02",
          "selected": true,
          "feasible": true,
          "rejection_reasons": [],
          "intercept_point": [
            -91.5534806,
            -1.7102526
          ],
          "intercept_hours": 2.878204,
          "completion_hours": 5.756408,
          "range_margin_km": 41.7,
          "source_badge": "DERIVED",
          "mission_score": 0.6334,
          "priority_score": 0.8104,
          "distance_km": 53.3,
          "travel_distance_km": 53.3,
          "estimated_collection_kg": 835.0,
          "alternatives": [
            {
              "usv_id": "usv_01",
              "cluster_id": "cluster_02",
              "feasible": false,
              "rejection_reasons": [
                "intercept_beyond_12h_forecast",
                "insufficient_range:requires_486.53km>remaining_120.00km"
              ],
              "one_way_distance_km": 243.26,
              "travel_distance_km": 486.53,
              "priority_score": 0.8104,
              "travel_penalty": 0.3,
              "capacity_penalty": 0.0642,
              "mission_score": 0.4462,
              "intercept_point": [
                -91.5684732,
                -1.5882441
              ],
              "intercept_hours": 12.0,
              "completion_hours": 52.540521,
              "range_margin_km": -366.53,
              "selected": false,
              "selection_reason": "infeasible"
            },
            {
              "usv_id": "usv_02",
              "cluster_id": "cluster_02",
              "feasible": true,
              "rejection_reasons": [],
              "one_way_distance_km": 26.65,
              "travel_distance_km": 53.3,
              "priority_score": 0.8104,
              "travel_penalty": 0.0842,
              "capacity_penalty": 0.0928,
              "mission_score": 0.6334,
              "intercept_point": [
                -91.5534806,
                -1.7102526
              ],
              "intercept_hours": 2.878204,
              "completion_hours": 5.756408,
              "range_margin_km": 41.7,
              "selected": true,
              "selection_reason": "best_feasible_mission_score"
            },
            {
              "usv_id": "usv_03",
              "cluster_id": "cluster_02",
              "feasible": false,
              "rejection_reasons": [
                "intercept_beyond_12h_forecast",
                "insufficient_range:requires_890.58km>remaining_90.00km",
                "insufficient_capacity:requires_835.00kg>capacity_700.00kg"
              ],
              "one_way_distance_km": 445.29,
              "travel_distance_km": 890.58,
              "priority_score": 0.8104,
              "travel_penalty": 0.3,
              "capacity_penalty": 0.1193,
              "mission_score": 0.3911,
              "intercept_point": [
                -91.5684732,
                -1.5882441
              ],
              "intercept_hours": 12.0,
              "completion_hours": 96.17488,
              "range_margin_km": -800.58,
              "selected": false,
              "selection_reason": "infeasible"
            }
          ]
        },
        {
          "usv_id": "usv_03",
          "cluster_id": "cluster_03",
          "selected": true,
          "feasible": true,
          "rejection_reasons": [],
          "intercept_point": [
            -88.8917745,
            0.9189001
          ],
          "intercept_hours": 4.12322,
          "completion_hours": 8.24644,
          "range_margin_km": 13.64,
          "source_badge": "DERIVED",
          "mission_score": 0.4592,
          "priority_score": 0.6851,
          "distance_km": 76.36,
          "travel_distance_km": 76.36,
          "estimated_collection_kg": 690.0,
          "alternatives": [
            {
              "usv_id": "usv_01",
              "cluster_id": "cluster_03",
              "feasible": false,
              "rejection_reasons": [
                "intercept_beyond_12h_forecast",
                "insufficient_range:requires_355.48km>remaining_120.00km"
              ],
              "one_way_distance_km": 177.74,
              "travel_distance_km": 355.48,
              "priority_score": 0.6851,
              "travel_penalty": 0.3,
              "capacity_penalty": 0.0531,
              "mission_score": 0.332,
              "intercept_point": [
                -88.9047162,
                1.0242559
              ],
              "intercept_hours": 12.0,
              "completion_hours": 38.389244,
              "range_margin_km": -235.48,
              "selected": false,
              "selection_reason": "infeasible"
            },
            {
              "usv_id": "usv_02",
              "cluster_id": "cluster_03",
              "feasible": false,
              "rejection_reasons": [
                "intercept_beyond_12h_forecast",
                "insufficient_range:requires_899.59km>remaining_95.00km"
              ],
              "one_way_distance_km": 449.79,
              "travel_distance_km": 899.59,
              "priority_score": 0.6851,
              "travel_penalty": 0.3,
              "capacity_penalty": 0.0767,
              "mission_score": 0.3084,
              "intercept_point": [
                -88.9047162,
                1.0242559
              ],
              "intercept_hours": 12.0,
              "completion_hours": 97.147556,
              "range_margin_km": -804.59,
              "selected": false,
              "selection_reason": "infeasible"
            },
            {
              "usv_id": "usv_03",
              "cluster_id": "cluster_03",
              "feasible": true,
              "rejection_reasons": [],
              "one_way_distance_km": 38.18,
              "travel_distance_km": 76.36,
              "priority_score": 0.6851,
              "travel_penalty": 0.1273,
              "capacity_penalty": 0.0986,
              "mission_score": 0.4592,
              "intercept_point": [
                -88.8917745,
                0.9189001
              ],
              "intercept_hours": 4.12322,
              "completion_hours": 8.24644,
              "range_margin_km": 13.64,
              "selected": true,
              "selection_reason": "best_feasible_mission_score"
            }
          ]
        }
      ],
      "route_sequences": [
        [
          [
            -89.8,
            -0.3
          ],
          [
            -90.2211706,
            -0.4256587
          ],
          [
            -89.8,
            -0.3
          ]
        ],
        [
          [
            -91.7,
            -1.9
          ],
          [
            -91.5534806,
            -1.7102526
          ],
          [
            -91.7,
            -1.9
          ]
        ],
        [
          [
            -88.6,
            1.1
          ],
          [
            -88.8917745,
            0.9189001
          ],
          [
            -88.6,
            1.1
          ]
        ]
      ],
      "total_distance_km": 227.4,
      "estimated_collection_kg": 2775.0,
      "capacity_utilization": 0.9569,
      "completion_time_hours": 10.56,
      "intercept_points": [
        {
          "cluster_id": "cluster_01",
          "usv_id": "usv_01",
          "position": [
            -90.2211706,
            -0.4256587
          ],
          "horizon_hours": 5.277657,
          "source_badge": "DERIVED"
        },
        {
          "cluster_id": "cluster_02",
          "usv_id": "usv_02",
          "position": [
            -91.5534806,
            -1.7102526
          ],
          "horizon_hours": 2.878204,
          "source_badge": "DERIVED"
        },
        {
          "cluster_id": "cluster_03",
          "usv_id": "usv_03",
          "position": [
            -88.8917745,
            0.9189001
          ],
          "horizon_hours": 4.12322,
          "source_badge": "DERIVED"
        }
      ],
      "rejected_assignments": [
        {
          "usv_id": "usv_02",
          "cluster_id": "cluster_01",
          "feasible": false,
          "rejection_reasons": [
            "intercept_beyond_12h_forecast",
            "insufficient_range:requires_476.99km>remaining_95.00km",
            "insufficient_capacity:requires_1250.00kg>capacity_900.00kg"
          ],
          "one_way_distance_km": 238.5,
          "travel_distance_km": 476.99,
          "priority_score": 0.9304,
          "travel_penalty": 0.3,
          "capacity_penalty": 0.1389,
          "mission_score": 0.4915,
          "intercept_point": [
            -90.2322147,
            -0.3357441
          ],
          "intercept_hours": 12.0,
          "completion_hours": 51.510857,
          "range_margin_km": -381.99
        },
        {
          "usv_id": "usv_03",
          "cluster_id": "cluster_01",
          "feasible": false,
          "rejection_reasons": [
            "intercept_beyond_12h_forecast",
            "insufficient_range:requires_483.42km>remaining_90.00km",
            "insufficient_capacity:requires_1250.00kg>capacity_700.00kg"
          ],
          "one_way_distance_km": 241.71,
          "travel_distance_km": 483.42,
          "priority_score": 0.9304,
          "travel_penalty": 0.3,
          "capacity_penalty": 0.1786,
          "mission_score": 0.4518,
          "intercept_point": [
            -90.2322147,
            -0.3357441
          ],
          "intercept_hours": 12.0,
          "completion_hours": 52.205393,
          "range_margin_km": -393.42
        },
        {
          "usv_id": "usv_01",
          "cluster_id": "cluster_02",
          "feasible": false,
          "rejection_reasons": [
            "intercept_beyond_12h_forecast",
            "insufficient_range:requires_486.53km>remaining_120.00km"
          ],
          "one_way_distance_km": 243.26,
          "travel_distance_km": 486.53,
          "priority_score": 0.8104,
          "travel_penalty": 0.3,
          "capacity_penalty": 0.0642,
          "mission_score": 0.4462,
          "intercept_point": [
            -91.5684732,
            -1.5882441
          ],
          "intercept_hours": 12.0,
          "completion_hours": 52.540521,
          "range_margin_km": -366.53
        },
        {
          "usv_id": "usv_03",
          "cluster_id": "cluster_02",
          "feasible": false,
          "rejection_reasons": [
            "intercept_beyond_12h_forecast",
            "insufficient_range:requires_890.58km>remaining_90.00km",
            "insufficient_capacity:requires_835.00kg>capacity_700.00kg"
          ],
          "one_way_distance_km": 445.29,
          "travel_distance_km": 890.58,
          "priority_score": 0.8104,
          "travel_penalty": 0.3,
          "capacity_penalty": 0.1193,
          "mission_score": 0.3911,
          "intercept_point": [
            -91.5684732,
            -1.5882441
          ],
          "intercept_hours": 12.0,
          "completion_hours": 96.17488,
          "range_margin_km": -800.58
        },
        {
          "usv_id": "usv_01",
          "cluster_id": "cluster_03",
          "feasible": false,
          "rejection_reasons": [
            "intercept_beyond_12h_forecast",
            "insufficient_range:requires_355.48km>remaining_120.00km"
          ],
          "one_way_distance_km": 177.74,
          "travel_distance_km": 355.48,
          "priority_score": 0.6851,
          "travel_penalty": 0.3,
          "capacity_penalty": 0.0531,
          "mission_score": 0.332,
          "intercept_point": [
            -88.9047162,
            1.0242559
          ],
          "intercept_hours": 12.0,
          "completion_hours": 38.389244,
          "range_margin_km": -235.48
        },
        {
          "usv_id": "usv_02",
          "cluster_id": "cluster_03",
          "feasible": false,
          "rejection_reasons": [
            "intercept_beyond_12h_forecast",
            "insufficient_range:requires_899.59km>remaining_95.00km"
          ],
          "one_way_distance_km": 449.79,
          "travel_distance_km": 899.59,
          "priority_score": 0.6851,
          "travel_penalty": 0.3,
          "capacity_penalty": 0.0767,
          "mission_score": 0.3084,
          "intercept_point": [
            -88.9047162,
            1.0242559
          ],
          "intercept_hours": 12.0,
          "completion_hours": 97.147556,
          "range_margin_km": -804.59
        }
      ],
      "feasibility_summary": {
        "assigned": 3,
        "unassigned_clusters": [],
        "battery_min_pct": 25.0,
        "range_policy": "round_trip",
        "forecast_horizon_hours": 12.0
      },
      "provenance": {
        "source_name": "MARINEX CLEANER",
        "source_mode": "derived",
        "source_badge": "DERIVED",
        "notes": "Simulation metrics from curated debris and simulated USVs. Constant-current interception; direct outbound/return paths, no land avoidance, collection duration or battery discharge model.",
        "environment_sources": [
          "open-meteo"
        ]
      },
      "replay_events": [
        {
          "timestamp": "2026-09-12T12:00:00Z",
          "event_type": "drift_forecast_updated",
          "details": {
            "clusters_forecasted": 3
          },
          "description": "Predicted drift for 3 debris clusters using latest environment data."
        },
        {
          "timestamp": "2026-09-12T12:00:00Z",
          "event_type": "intercept_chosen",
          "details": {
            "usv_id": "usv_01",
            "cluster_id": "cluster_01"
          },
          "description": "USV usv_01 assigned to intercept cluster cluster_01."
        },
        {
          "timestamp": "2026-09-12T12:00:00Z",
          "event_type": "intercept_chosen",
          "details": {
            "usv_id": "usv_02",
            "cluster_id": "cluster_02"
          },
          "description": "USV usv_02 assigned to intercept cluster cluster_02."
        },
        {
          "timestamp": "2026-09-12T12:00:00Z",
          "event_type": "intercept_chosen",
          "details": {
            "usv_id": "usv_03",
            "cluster_id": "cluster_03"
          },
          "description": "USV usv_03 assigned to intercept cluster cluster_03."
        },
        {
          "timestamp": "2026-09-12T12:00:00Z",
          "event_type": "alternatives_rejected",
          "details": {
            "rejected_count": 6
          },
          "description": "Rejected 6 assignments due to capacity or range constraints."
        }
      ]
    },
    "usvs": [
      {
        "usv_id": "usv_01",
        "location": [
          -89.8,
          -0.3
        ],
        "capacity_kg": 1300.0,
        "battery_pct": 95.0,
        "remaining_range_km": 120.0,
        "status": "idle",
        "speed_kn": 5.0,
        "source_badge": "SIMULATED"
      },
      {
        "usv_id": "usv_02",
        "location": [
          -91.7,
          -1.9
        ],
        "capacity_kg": 900.0,
        "battery_pct": 82.0,
        "remaining_range_km": 95.0,
        "status": "idle",
        "speed_kn": 5.0,
        "source_badge": "SIMULATED"
      },
      {
        "usv_id": "usv_03",
        "location": [
          -88.6,
          1.1
        ],
        "capacity_kg": 700.0,
        "battery_pct": 68.0,
        "remaining_range_km": 90.0,
        "status": "idle",
        "speed_kn": 5.0,
        "source_badge": "SIMULATED"
      }
    ],
    "context": {
      "source_name": "NOAA Office of Response and Restoration",
      "dataset": "MDMAP National Survey / InPort 73092",
      "source_mode": "reference",
      "source_badge": "REFERENCE",
      "source_url_or_id": "https://www.fisheries.noaa.gov/inport/item/73092",
      "observed_at": "2024",
      "retrieved_at": "2026-09-12",
      "cached": true,
      "cache_version": "cycle-a-v1",
      "notes": "Candidate shoreline survey sites, used as methodological context only. No NOAA floating-debris coordinates or measured masses are used by this Galapagos scenario. Offshore targets are curated simulated inputs."
    }
  },
  "supervisor": {
    "last_decision": null
  }
};
